### ISSUE TITLE
Runtime exception when writing to mp3 files: Used by another process

### ISSUE THREAD

**Issue by ZiadElGendy** [ZiadElGendy/mp3-tag-editor#4]
An IOException was thrown when writing to mp3 files to modify tag, not sure if this is universal or just a problem with my system.

**Attempted solutions:**
-Moved sample mp3s away from local repository folder

**Console output:**
```Unhandled exception. System.IO.IOException: The process cannot access the file 'D:\Documents\Programming\Group Project\2023\ZMBY 3\Sample MP3s\01 No Escape.mp3' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)     
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Id3.Mp3..ctor(String filename, Mp3Permissions permissions)
   at MP3_Tag_Editor.Mp3FileManager.LoadMp3FileFromPath(String filePath) in D:\Documents\Programming\Group Project\2023\ZMBY 3\mp3-tag-editor\MP3 Tag Editor\Mp3FileManager.cs:line 36
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at MP3_Tag_Editor.Mp3FileManager.LoadMp3FilesFromDirectory(String directoryPath) in D:\Documents\Programming\Group Project\2023\ZMBY 3\mp3-tag-editor\MP3 Tag Editor\Mp3FileManager.cs:line 61
   at MP3_Tag_Editor.Mp3FileManager.LoadMp3Files(String path) in D:\Documents\Programming\Group Project\2023\ZMBY 3\mp3-tag-editor\MP3 Tag Editor\Mp3FileManager.cs:line 23
   at MP3_Tag_Editor.Mp3Manager.LoadFilesToMemory(String inputFilePath) in D:\Documents\Programming\Group Project\2023\ZMBY 3\mp3-tag-editor\MP3 Tag Editor\Mp3Manager.cs:line 144
   at MP3_Tag_Editor.Mp3Manager.ModifyMp3Tags(String inputFilePath, String selectedProperty, String inputValue) in D:\Documents\Programming\Group Project\2023\ZMBY 3\mp3-tag-editor\MP3 Tag Editor\Mp3Manager.cs:line 19
   at MP3_Tag_Editor.Mp3Manager.ModifyMp3TagsTest() in D:\Documents\Programming\Group Project\2023\ZMBY 3\mp3-tag-editor\MP3 Tag Editor\Mp3Manager.cs:line 171
   at MP3_Tag_Editor.Program.Main(String[] args) in D:\Documents\Programming\Group Project\2023\ZMBY 3\mp3-tag-editor\MP3 Tag Editor\Program.cs:line 10

Process finished with exit code -532,462,766.
```

**Comment by mazenwkamel** [comment]
Steps to recreate the issue?

**Comment by ZiadElGendy** [comment]
Run `Mp3Manager.ModifyMp3TagsTest()` on the `modify-tag` branch, changing the path to a directorycontaining mp3 files on your PC.

**Comment by mazenwkamel** [comment]
Fixed. Mp3 files had to get disposed of after operations were done. Otherwise, they were still considered open.

```
    private static void LoadFilesToMemory(string inputFilePath)
    {
        Mp3FileManager.DisposeMp3Files(_workingMp3Files);
       // code
    }
```
